# listen port
server:
  port: 8080

# registry location(eureka)
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  prefix: /api

# sleuth/zipkin
spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://localhost:9411/

# disable hystrix timeout
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

management:
  endpoints:
    web:
      exposure:
        include: routes
#  security:
#    enabled: false
#security:
#  basic:
#    enabled: false